### ISSUE TITLE
create encryption key for rememberMe manager

### ISSUE THREAD

**Issue by tbarker9** [pledbrook/grails-shiro#28]
on this [line](https://github.com/pledbrook/grails-shiro/blob/master/ShiroGrailsPlugin.groovy#L129), the shiro plugin creates a remember me manager using the default settings from shiro.  Unfortunately this means it is using a hardcoded cypher key to encrypt and decrypt the cookie as seen in this [line](https://github.com/apache/shiro/blob/1.0.x/core/src/main/java/org/apache/shiro/mgt/AbstractRememberMeManager.java#L109).  In theory, a malicious hacker with knowledge of a user name could create a serialized `PrincipalCollection` with the hard coded key and appear remembered to a web application.  This is of course easy to fix; just do something like `shiroRememberMeManager.setCypherKey(myKey)` in a bootstrap file.  That said I suspect most users of this plugin are blindly using it, assuming it is more secure than this out of the box.  

So I propose that a key file be generated by default and placed under `~/.grails` and used to encrypt the cookie.  Maybe allow the user to put a key in the Config instead.  The above vulnerability may never happen due to its complexity, but the fix is pretty easy.  At very least the vulnerability and work around should be documented beyond this issue.  

I have to disclose that I am not a security expert and I could be way off the mark here.  So if I am missing something, please tell me.

**Comment by carlosorrego** [comment]
rememberMe does not work for me on grails 3.3.9
i have done everything in the docs

**Comment by pmcneil** [comment]
@carlosorrego Try the new plugin https://github.com/nerdErg/grails-shiro, doco also at https://nerderg.com/docs/shiro/guide.html#security-shiro, Plugin page http://plugins.grails.org/plugin/nerderg/grails-shiro

This repo is archive
