### ISSUE TITLE
Hitting Ctrl+C during Grails Shiro config has left app completely broken!

### ISSUE THREAD

**Issue by hotmeatballsoup** [pledbrook/grails-shiro#54]
Grails 2.4.5 and Grails Shiro 1.2.1 here.

I _had_ Shiro configured and working perfectly (when I go to an authenticated URL - as defined by the security filter - Grails Shiro intercepts and redirects to `login.gsp`, etc.) Authentication/authrorization _was_ working flawlessly (upon logging in, the `MyAppDbRealm` class was invoked to auth the user, etc.).

This morning I was doing some local dev and ran `grails run-app`. About half-way through the `run-app`, I realized I needed to change something and hit `Ctrl+C` while Grails was configuring Shiro (according to the console output). **I am now completely unable to `run-app` and it seems that hitting `Ctrl+C` during Grails Shiro config has left the app in a broken/blocking state.**

So now when I do `grails run-app --stacktrace` I get:

```
| Compiling 27 source files.....
| Error Error generating web.xml file (Use --stacktrace to see the full trace)
| Packaging Grails application.....
| Error Error generating web.xml file (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
groovy.lang.MissingPropertyException: No such property: shiro for class: java.lang.String
    at ShiroGrailsPlugin$_closure4_closure30_closure34.doCall(ShiroGrailsPlugin.groovy:248)
    at ShiroGrailsPlugin$_closure4_closure30_closure34.doCall(ShiroGrailsPlugin.groovy)
    at ShiroGrailsPlugin$_closure4_closure30.doCall(ShiroGrailsPlugin.groovy:243)
    at ShiroGrailsPlugin$_closure4_closure30.doCall(ShiroGrailsPlugin.groovy)
    <enormous stack trace omitted for brevity>
    at gant.Gant.executeTargets(Gant.groovy:590)
| Error Error generating web.xml file
```

I've done everything I could think of (`grails clean`, `grails clean-all`, `grails refresh-dependencies`, etc.). **Please advise as I am unable to do any dev work whatsoever!!!**

**Comment by pmcneil** [comment]
you probably just have a grails process running in the background. Try killing all the Java processes youhave running and starting again... or reboot if you use windows.

**Comment by pmcneil** [comment]
oh and do a clean all :-)

**Comment by hotmeatballsoup** [comment]
Thanks @pmcneil but restarting my machine and `grails clean-all` aren't fixing this. I have verified there are no running Grails processes. Any thoughts?

**Comment by hotmeatballsoup** [comment]
OK after looking at this yesterday, I'm pretty sure this *isn't* a Grails Shiro bug at all but wanted to post the solution here in case anyone disagrees. At the very top of my `Config.groovy` I have the following two lines:

    String configFileAbsPath = System.getProperty('configFileAbsPath')
    grails.config.locations = [ "file:${configFileAbsPath}" ]

So I'm allowing the user to specify an external config file anywhere in their system and to pass it in like so:

    grails -DconfigFileAbsPath=<wherever> run-app

When my config file resides in a directory that my user owns, such as `~/tmp`, then the app works just fine:

    // This works
    grails -DconfigFileAbsPath=/Users/myuser/tmp/myapp.properties run-app

**However** if I don't *own* the parent directory of the config file, then that is when this error crops up:

    // Produces this weird 'MissingPropertyException' on some 'shiro' property...
    grails -DconfigFileAbsPath=/opt/myapp/myapp.properties run-app

And the problem was that - at the time that I reported this issue - the config file was under `/opt/myapp`. Once I moved it under `/Users/myuser/tmp` it stopped doing this.

**Any thoughts here?!?**

**Comment by pmcneil** [comment]
I'm guessing that when the config doesn't exist the shiro plugin code:

if (application.config.security.shiro.filter.config) {...

is getting a string back for "application.config.security"


On 27/10/15 21:58, hotmeatballsoup wrote:
>
> OK after looking at this yesterday, I'm pretty sure this /isn't/ a 
> Grails Shiro bug at all but wanted to post the solution here in case 
> anyone disagrees. At the very top of my |Config.groovy| I have the 
> following two lines:
>
> |String configFileAbsPath = System.getProperty('configFileAbsPath') 
> grails.config.locations = [ "file:${configFileAbsPath}" ] |
>
> So I'm allowing the user to specify an external config file anywhere 
> in their system and to pass it in like so:
>
> |grails -DconfigFileAbsPath=<wherever> run-app |
>
> When my config file resides in a directory that my user owns, such as 
> |~/tmp|, then the app works just fine:
>
> |// This works grails 
> -DconfigFileAbsPath=/Users/myuser/tmp/myapp.properties run-app |
>
> *However* if I don't /own/ the parent directory of the config file, 
> then that is when this error crops up:
>
> |// Produces this weird 'MissingPropertyException' on some 'shiro' 
> property... grails -DconfigFileAbsPath=/opt/myapp/myapp.properties 
> run-app |
>
> And the problem was that - at the time that I reported this issue - 
> the config file was under |/opt/myapp|. Once I moved it under 
> |/Users/myuser/tmp| it stopped doing this.
>
> *Any thoughts here?!?*
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pledbrook/grails-shiro/issues/54#issuecomment-151455698>.
>

-- 
web: http://nerderg.com
Twitter: http://twitter.com/pmcneil
Google+: https://plus.google.com/u/0/communities/110661434396927001866
