### ISSUE TITLE
GettingStarted and Bootstrap example code - Sha256Hash password lack of salt creates security risk for plugin users

### ISSUE THREAD

**Issue by edwardotis** [pledbrook/grails-shiro#58]
I just used this plugin in a grails 2.5 project. I was going through the code, and I see that the GettingStarted and Bootstrap password hashing implementation introduces  security risks, as documented by the Shiro Project:
"
Salting and Multiple Hash Iterations

Because simple hashing is usually not good enough for secure applications, this class also supports 'salting' and multiple hash iterations. Please read this excellent Hashing Java article to learn about salting and multiple iterations and why you might want to use them. (Note of sections 5 "Why add salt?" and 6 "Hardening against the attacker's attack"). We should also note here that all of Shiro's Hash implementations (for example, Md5Hash, Sha1Hash, etc) support salting and multiple hash iterations via overloaded constructors.
Real World Case Study

In April 2010, some public Atlassian Jira and Confluence installations (Apache Software Foundation, Codehaus, etc) were the target of account attacks and user accounts were compromised. The reason? Jira and Confluence at the time did not salt user passwords and attackers were able to use dictionary attacks to compromise user accounts (Atlassian has since fixed the problem of course).
The lesson?

ALWAYS, ALWAYS, ALWAYS SALT USER PASSWORDS!
"
http://shiro.apache.org/static/current/apidocs/org/apache/shiro/authc/credential/HashedCredentialsMatcher.html

**Comment by pmcneil** [comment]
I'm implementing BCrypt with a configurable number of rounds in the new version.
