### ISSUE TITLE
Grails 3.2.x support?

### ISSUE THREAD

**Issue by aadrian** [pledbrook/grails-shiro#62]
Hi,

any chance updating the plug-in to support Grails 3.3.x ?

Thank you.

**Comment by pmcneil** [comment]
I'm going to split the grails 3 plugin off to a separate repo and publish it properly right now, and in that process upgrade to 3.3.10 as it's just not working here. I'll let you all know where and when the new plugin surfaces.

**Comment by pmcneil** [comment]
new plugin, see http://plugins.grails.org/plugin/nerderg/grails-shiro
