### ISSUE TITLE
Shiro authentication and authorization too?

### ISSUE THREAD

**Issue by aadrian** [pledbrook/grails-shiro#63]
Hi,

I the docs is mentioned:
`"The majority of the authentication and authorization work is still done by Spring Security. "`

Any chance having Shiro based authentication and authorization too? The whole point of using Shiro is to have those done by Shiro :( .

Thank you.

**Comment by pmcneil** [comment]
I know this is old, but I think you are reading the spring security shiro plugin documentation.
